<?php

session_start();
print_r($_POST);
echo '<br>';
echo count($_POST);
echo '<br>';



include 'C:\xampp\php\PHPExcel\Classes\PHPExcel.php';
// Create new PHPExcel object
$objPHPExcel = new PHPExcel();
// Set properties
$objPHPExcel->getProperties()->setCreator("Innovative Data Solutions");
$objPHPExcel->getProperties()->setLastModifiedBy($_SESSION['names']);
$objPHPExcel->getProperties()->setTitle("IDS Official Quote Document");
$objPHPExcel->getProperties()->setSubject("IDS Official Quote Document");
$objPHPExcel->getProperties()->setDescription("IDS Official Quote Document generated by " . $_SESSION['names']);
$objPHPExcel->getActiveSheet()->setTitle('Quote_' . date('Y-m-d'));

//set appropriates cell widths for various columns
$objPHPExcel->setActiveSheetIndex(0);
$objPHPExcel->getActiveSheet()->getColumnDimension('D')->setWidth(30);
$objPHPExcel->getActiveSheet()->getColumnDimension('E')->setWidth(20);
$objPHPExcel->getActiveSheet()->getColumnDimension('G')->setWidth(10);
$objPHPExcel->getActiveSheet()->getColumnDimension('H')->setWidth(15);

//set headers as appropriates
$objPHPExcel->getActiveSheet()->SetCellValue('D5', 'DATE');
$objPHPExcel->getActiveSheet()->SetCellValue('E5', date('Y-m-d'));
$objPHPExcel->getActiveSheet()->SetCellValue('D6', 'COUNTRY');
$objPHPExcel->getActiveSheet()->SetCellValue('E6', 'MULTICOUNTRY');
$objPHPExcel->getActiveSheet()->SetCellValue('D7', 'SUPPLIER');
$objPHPExcel->getActiveSheet()->SetCellValue('E7', 'IDS');
$objPHPExcel->getActiveSheet()->SetCellValue('D8', 'CURRENCY');
$objPHPExcel->getActiveSheet()->SetCellValue('E8', $_POST['curr']);
$objPHPExcel->getActiveSheet()->SetCellValue('D11', 'SUBJECT');
$objPHPExcel->getActiveSheet()->SetCellValue('E11', 'QUANTITY');
$objPHPExcel->getActiveSheet()->SetCellValue('F11', 'DAYS');
$objPHPExcel->getActiveSheet()->SetCellValue('G11', 'DAILY COST');
$objPHPExcel->getActiveSheet()->SetCellValue('H11', 'TOTAL');

//loop through array to write values to appropriate cells
$j = 1;
if (!isset($_POST['tax_rate'])) {
    $_POST['tax_rate'] = 0;
}
$table_length = (count($_POST) - 16) / 4;
$net = $total = $tax = $euro_total = $dollar_total = array();
$grand_total_naira = $grand_total_dollar = $grand_total_euro = 0;
$dollar_cost = $euro_cost = array();
for ($i = 1; $i <= $table_length; $i++) {

    $net[$i] = intval($_POST['quantity_' . $i]) * intval($_POST['days_' . $i]) * intval($_POST['cost_' . $i]);
    $tax[$i] = $net[$i] * floatval($_POST['tax_rate'] / 100);

    $total[$i] = intval($_POST['quantity_' . $i]) * intval($_POST['days_' . $i]) * intval($_POST['cost_' . $i]);
//   $total[$i] = $net[$i] - $tax[$i];
    $grand_total_naira = $grand_total_naira + $total[$i];

    //calculate values in dollars
    $dollar_cost[$i] = intval($_POST['cost_' . $i]) / intval($_POST['dollar_exch']);
    $dollar_total[$i] = intval($_POST['quantity_' . $i]) * intval($_POST['days_' . $i]) * $dollar_cost[$i];
    //$dollar_total[$i] = $total[$i] / $_POST['dollar_exch'];
    $grand_total_dollar = $grand_total_dollar + $dollar_total[$i];

    //calculate euro values
    $euro_cost[$i] = intval($_POST['cost_' . $i]) / intval($_POST['euro_exch']);
    $euro_total[$i] = intval($_POST['quantity_' . $i]) * intval($_POST['days_' . $i]) * $euro_cost[$i];
   // $euro_total[$i] = $total[$i] / $_POST['euro_exch'];
    $grand_total_euro = $grand_total_euro + $euro_total[$i];

    echo 'Net: ' . $net[$i] . '    Tax: ' . $tax[$i] . '     Gross: ' . $total[$i];
    echo '<br>';
    $k = $i + 11;
    $objPHPExcel->getActiveSheet()->SetCellValue('D' . $k, $_POST['item_' . $j]);
    $objPHPExcel->getActiveSheet()->SetCellValue('E' . $k, $_POST['quantity_' . $j]);
    $objPHPExcel->getActiveSheet()->SetCellValue('F' . $k, $_POST['days_' . $j]);
    if ($_POST['curr'] == "Nigeria Naira") {
        $objPHPExcel->getActiveSheet()->SetCellValue('G' . $k, number_format($_POST['cost_' . $j], 2));
        $objPHPExcel->getActiveSheet()->SetCellValue('H' . $k, number_format($total[$i], 2));
    } elseif ($_POST['curr'] == "U.S Dollars") {
        $objPHPExcel->getActiveSheet()->SetCellValue('G' . $k, $dollar_cost[$i], 2);
        $objPHPExcel->getActiveSheet()->SetCellValue('H' . $k, number_format($dollar_total[$i], 2));
    } elseif ($_POST['curr'] == "Euros") {
        $objPHPExcel->getActiveSheet()->SetCellValue('G' . $k, $euro_cost[$i], 2);
        $objPHPExcel->getActiveSheet()->SetCellValue('H' . $k, number_format($euro_total[$i], 2));
    }

    $j++;
}
echo "<br>The last row is: ".$k;
//calculate cpi for each currency

$cpi_naira = $grand_total_naira / intval($_POST['sample_size']);
$cpi_dollar = $grand_total_dollar / intval($_POST['sample_size']);
$cpi_euro = $grand_total_euro / intval($_POST['sample_size']);

//write CPI value
$objPHPExcel->getActiveSheet()->SetCellValue('D'.++$k, 'CPI');
if ($_POST['curr'] == "Nigeria Naira") {
    $objPHPExcel->getActiveSheet()->getStyle('H'.$k)->getNumberFormat()->setFormatCode('N#,##0.00');
    $objPHPExcel->getActiveSheet()->SetCellValue('H' . $k, $cpi);
}
elseif ($_POST['curr'] == "U.S Dollars") {
    $objPHPExcel->getActiveSheet()->getStyle('H'.$k)->getNumberFormat()->setFormatCode('$#,##0.00');
    $objPHPExcel->getActiveSheet()->SetCellValue('H' . $k, $cpi_dollar);
}
elseif ($_POST['curr'] == "Euros") {
    $objPHPExcel->getActiveSheet()->getStyle('H'.$k)->getNumberFormat()->setFormatCode('EURO#,##0.00');
    $objPHPExcel->getActiveSheet()->SetCellValue('H' . $k,$cpi_euro);
}

//set border color and styles for various ranges
$objPHPExcel->getActiveSheet()->getStyle("D5:E8")->applyFromArray(
        array(
            'borders' => array(
                'allborders' => array(
                    'style' => PHPExcel_Style_Border::BORDER_THICK,
                    'color' => array('rgb' => '000080')
                )
            )
        )
);
$objPHPExcel->getActiveSheet()->getStyle("D11:H".$k)->applyFromArray(
        array(
            'borders' => array(
                'allborders' => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN,
                    'color' => array('rgb' => '000080')
                )
            )
        )
);

//merge the cells and collor with yellow 
$objPHPExcel->getActiveSheet()->mergeCells("D".$k.":G".$k);
$objPHPExcel->getActiveSheet()->getStyle('D'.$k)->getFill()
->setFillType(PHPExcel_Style_Fill::FILL_SOLID)
->getStartColor()->setARGB('FFFFFF00');

//create an object drawing for the logo
$gdImage = imagecreatefromjpeg('images/IDS Logo.jpg');
// Add a drawing to the worksheetecho date('H:i:s') . " Add a drawing to the worksheet\n";
$objDrawing = new PHPExcel_Worksheet_MemoryDrawing();
$objDrawing->setName('IDS Logo');
$objDrawing->setDescription('IDS Logo');
$objDrawing->setImageResource($gdImage);
$objDrawing->setRenderingFunction(PHPExcel_Worksheet_MemoryDrawing::RENDERING_JPEG);
$objDrawing->setMimeType(PHPExcel_Worksheet_MemoryDrawing::MIMETYPE_DEFAULT);
$objDrawing->setHeight(50);
$objDrawing->setCoordinates('A1');
$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());
$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
//$objWriter->save(str_replace('.php', '.xlsx', __FILE__));
$file_no = rand(0, 9);
//$objWriter->save(str_replace(__FILE__,'folder_path/filename.xlsx',__FILE__));
$objWriter->save('quote' . date('Y.m.d') . '_' . $file_no . '.xlsx');
// Echo done
echo '<br>'. date('H:i:s') . " Done writing file.\r\n";
echo '<br>' . $_POST['curr'];
